abstract class AppRoutes {
  AppRoutes._();
  static const splash = _Paths.splash;
  static const starter = _Paths.starter;
  static const login = _Paths.login;
  static const register = _Paths.register;
  static const userHome = _Paths.userHome;
  static const adopt = _Paths.adopt;
  static const event = _Paths.event;
  static const chat = _Paths.chat;
  static const profile = _Paths.profile;
  static const editProfile = _Paths.editProfile;
  static const adoptionRequest = _Paths.adoptionRequest;
  static const adoptionStatus = _Paths.adoptionStatus;
  static const verification = _Paths.verification;
  static const shelterHome = _Paths.shelterHome;
  static const shelterAddPet = _Paths.shelterAddPet;
  static const shelterAddEvent = _Paths.shelterAddEvent;
  static const shelterManagePets = _Paths.shelterManagePets;
  static const shelterManageEvents = _Paths.shelterManageEvents;
  static const shelterEditPet = _Paths.shelterEditPet;
  static const shelterEditEvent = _Paths.shelterEditEvent;
  static const editShelterProfile = _Paths.editShelterProfile;
  static const shelterProfile = _Paths.shelterProfile;
  static const shelterAdoptionManagement = _Paths.shelterAdoptionManagement;
  static const adminHome = _Paths.adminHome;
  static const adminUserManagement = _Paths.adminUserManagement;
  static const adminShelterVerification = _Paths.adminShelterVerification;
  static const adminReportManagement = _Paths.adminReportManagement;
  static const adminReportDetails = _Paths.adminReportDetails;
  static const suspendedAccount = _Paths.suspendedAccount;
  static const selectEntityToReport = _Paths.selectEntityToReport;
  static const reportForm = _Paths.reportForm;
}

abstract class _Paths {
  _Paths._();
  static const splash = '/splash';
  static const starter = '/starter';
  static const login = '/login';
  static const register = '/register';
  static const userHome = '/user-home';
  static const adopt = '/adopt';
  static const event = '/event';
  static const chat = '/chat';
  static const profile = '/profile';
  static const editProfile = '/edit-profile';
  static const adoptionRequest = '/adoption-request';
  static const adoptionStatus = '/adoption-status';
  static const verification = '/verification';
  static const shelterHome = '/shelter-home';
  static const shelterAddPet = '/shelter/add-pet';
  static const shelterAddEvent = '/shelter/add-event';
  static const shelterManagePets = '/shelter/manage-pets';
  static const shelterManageEvents = '/shelter/manage-events';
  static const shelterEditPet = '/shelter/edit-pet';
  static const shelterEditEvent = '/shelter/edit-event';
  static const editShelterProfile = '/shelter/edit-profile';
  static const shelterProfile = '/shelter-profile';
  static const shelterAdoptionManagement = '/shelter/adoption-management';
  static const adminHome = '/admin-home';
  static const adminUserManagement = '/admin/user-management';
  static const adminShelterVerification = '/admin/shelter-verification';
  static const adminReportManagement = '/admin/report-management';
  static const adminReportDetails = '/admin/report-details';
  static const suspendedAccount = '/suspended-account';
  static const selectEntityToReport = '/select-entity-to-report';
  static const reportForm = '/report-form';
}
